#!/bin/bash
#
# /etc/rc.d/init.d/chupa-text
#
# chkconfig: 2345 80 20
# description: Text extraction server.
#
### BEGIN INIT INFO
# Provides:          chupa-text
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Text extraction server
# Description:       Text extraction server
### END INIT INFO

# Source function library.
. /etc/init.d/functions

name="ChupaText"
prog="chupa-text"

RETVAL=0


start() {
    echo -n "Starting $name: "
    docker run \
	   --name $prog \
	   --detach \
	   --rm \
	   --publish 127.0.0.1:20080:3000 \
	   groonga/chupa-text:debian-latest
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$prog
    return $RETVAL
}

stop() {
    echo -n "Shutting down $name: "
    docker kill $prog
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$prog
    return $RETVAL
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    condrestart)
        [ -f /var/lock/subsys/$prog ] && restart || :
        ;;
    status)
        docker ps --filter "name=$prog"
        ;;
    *)
        echo "Usage: $prog {start|stop|restart|condrestart|status}"
        exit 1
        ;;
esac
exit $?
